apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hasher
  name: hasher
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasher
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hasher
    spec:
      containers:
      - image: dockercoins/hasher:v0.1
        imagePullPolicy: IfNotPresent
        name: hasher
